### ISSUE TITLE
suggestion: add context menu item to files as well as directories, to create a new file in the same directory as the selected file

### ISSUE THREAD

**Issue by fschwiet** [jacokok/csharp-stretch#1]
Thanks for the great extension, its been very helpful.

Often when I want to create a new C# file, I want to put it in the same directory as the file I'm working on. However due to the mess of expanded directories and files it can take awhile to navigation the explorer to find that directory to create a file. If the "Create new c# file" was available in the context menu for the file I'm currently at then it would be a lot easier.

I admit it might feel a bit tacky... To keep it clean maybe only extend the context menu for c# files.

Just a thought, thanks again.

**Comment by jacokok** [comment]
I added a new setting to allow you to enable showing context menu on files.

![image](https://user-images.githubusercontent.com/5338052/185262081-68206a1e-d475-42d8-a5ed-d85d503f3e75.png)

**Comment by fschwiet** [comment]
Thanks, I checked and its working for me.
